### ISSUE TITLE
[Images App] Resizing controller affects viewers

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#192] opened 2019-08-05 12:29 UTC
If the control page for an image section is open in a web-browser, then resizing the browser window (e.b., by switching between full-screen and left-half-screen) changes what is displayed by the viewers.

Specifically, a section of the image can be hidden.

I thought I had reported this a few months ago but seem to have only described it verbally rather than opening an issue.

**Comment by senakafdo** [comment] 2019-08-06 00:15
This is a duplicate of #123.

**Closed by senakafdo** 2019-08-06 00:15 UTC
Labels: duplicate
