### ISSUE TITLE
OVE Video Controller is blank unless OVE Clients connected

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#151] opened 2019-04-15 09:20 UTC
If a section is created and the controller page is opened before the OVE Clients for the corresponding space have been created, then the video is not displayed in the controller. It is, however, loaded: it is just not displayed.

This is confusing for a user, and gives the impression that there is a problem with the sections' state, rather than with the OVE Clients.

**Comment by senakafdo** [comment] 2019-04-15 18:36
So, we cannot load the video on the controller while it is being buffered on the clients. And, the clients can be launched after a considerable delay in some situations. I think the resolution of #152 which will introduce control buttons for the videos app can either provide some graphical feedback to the end user that the video is not fully loaded. Or we can force the playback of the video if someone presses the play button after waiting for a pre-defined timeout.

**Comment by senakafdo** [comment] 2019-04-21 01:17
@jamesscottbrown, if this was due to the bug in the Asset Manager that was just fix, please close this issue. If not, please provide some steps on how to reproduce the issue.

**Comment by jamesscottbrown** [comment] 2019-04-29 08:49
To reproduce, create a video section in a space for which the OVE Clients are not open, then open the controller. The `video_player` iframe will have attribute `style="display: none"`.

However, if the OVE Client was already open in a browser, the `video_player` in the controller page will be visible.

**Comment by jamesscottbrown** [comment] 2019-04-30 15:09
This could be resolved by displaying a message explaining that the OVE Clients are not connected.

**Closed** 2019-04-30 20:02 UTC
