### ISSUE TITLE
Chrome audio autoplay policy causes problems

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#131] opened 2019-03-07 12:17 UTC
I tried testing the Audio App just now, and while audio started playing in the controller, it did not start in the viewers. Instead, this warning message was displayed in the console:

*The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu*

**Comment by senakafdo** [comment] 2019-04-06 19:42
This can only be fixed via proper documentation on how to configure Chrome. This is not a bug and nothing to be fixed at an app-level.

**Closed by senakafdo** 2019-04-06 19:42 UTC
Labels: duplicate
